data <- read.table("./data/RDA/household_power_consumption.txt", header=TRUE, sep=";", stringsAsFactors=FALSE, dec=".")
setwd("./data/RDA")

datetime <- strptime(paste(data$Date, data$Time, sep=" "), "%d/%m/%Y %H:%M:%S")
png("plot3.png")
plot(datetime,data$Sub_metering_1,type="l",xlab="",ylab="Energy sub metering")
lines(datetime,data$Sub_metering_2,type="l",col="red")
lines(datetime,data$Sub_metering_3,type="l",col="blue")
legend("topright",c("Sub_metering_1", "Sub_metering_2", "Sub_metering_3"),lty=1,lwd=2.5, col=c("black", "red", "blue"))
dev.off()